version: '3'
services:
  server:
    build: AvitoProject/
    ports:
      - "5555:5555"
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    build: Postgres/
    ports:
      - "5555:5432"

