version: '3'
services:
  server:
    build: AvitoProject/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: composepostgres
    build: Postgres/
  swagger:
    build: Swagger/
    ports:
      - "8081:8081"

